# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DNS-SEC
version:      0.12_02
version_from: SEC.pm
installdirs:  site
requires:
    Crypt::OpenSSL::Bignum:        0.03
    Crypt::OpenSSL::DSA:           0.1
    Crypt::OpenSSL::RSA:           0.19
    Digest::BubbleBabble:          0.01
    Digest::SHA1:                  0
    File::Basename:                0
    Math::BigInt:                  0
    MIME::Base64:                  0
    Net::DNS:                      0.44
    Test::More:                    0.47
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.26
